### ISSUE TITLE
Automate One Order

### ISSUE THREAD

**Issue by kchevali** [kchevali/CakeManiac#15]
# Description
Complete a single order.

# Tasks
- [ ] Go to the first customer location.
- [ ] Wait for the customer to request a menu.
- [ ] Provide a menu for the customer.
- [ ] Go to the oven.
- [ ] Wait for the customer to make their order.
- [ ] Interpret the order.
- [ ] Select the cake type.
- [ ] Wait for the cake to bake.
- [ ] Pick up the cake.
- [ ] Select the frosting type.
- [ ] Wait for the frosting to complete.
- [ ] Pick up the cake.
- [ ] Select the customer.
- [ ] Wait for the customer to make the payment.
- [ ] Select the payment.
