### ISSUE TITLE
Optimize Multiple Orders

### ISSUE THREAD

**Issue by kchevali** [kchevali/CakeManiac#16]
# Description
We would like to handle multiple order concurrently.

# Tasks
- [ ] Create a queue for each step of the ordering, baking and payment process.
- [ ] Use the progress and walking times to determine the fastest order of events to complete every order available.
- [ ] Include predictions of the arrival time of the next customer.
