### ISSUE TITLE
Detect Customer Patience

### ISSUE THREAD

**Issue by kchevali** [kchevali/CakeManiac#18]
# Description
The patience of each customer is represented by the number of hearts present.

# Task

- [ ] Identify the location of the hearts per customer.
- [ ] Identify the location of each heart.
- [ ] Compare pixels to count the number of hearts
