### ISSUE TITLE
Screen Capture

### ISSUE THREAD

**Issue by kchevali** [kchevali/CakeManiac#2]
# Description
Capture and store the pixels for the game area.

# Tasks
- [ ] Install a screen capture library for python and it should be fast and cross-platform (i.e. MSS).
- [ ] Capture a portion of the screen by a position and dimensions.
- [ ] Define a search rectangle and detect the game area. Alternative: hard code location.
- [ ] Define a refresh rate over a unit of time.

# Resources
- [MSS](https://python-mss.readthedocs.io/usage.html) library.

# Prerequisite Issues
- #1
