### ISSUE TITLE
Game Purchasing

### ISSUE THREAD

**Issue by kchevali** [kchevali/CakeManiac#26]
# Description
After each level, we have the option to purchase a new appliance or upgrade.

# Tasks
- [ ] Determine the cheapest purchase that can be made.
- [ ] Determine the current amount of money available.
- [ ] Make a purchase and repeat if possible.
