### ISSUE TITLE
Automate the End of the Level

### ISSUE THREAD

**Issue by kchevali** [kchevali/CakeManiac#27]
# Description
Complete the level.

# Tasks
- [ ] Detect when the last customer has left.
- [ ] Collect the final payment(s).
- [ ] Determine if the level was beat or not.
- [ ] Read the total amount of money earned in the level.
- [ ] Advance to the next screen.
