### ISSUE TITLE
Handling Multiple Customer Timings

### ISSUE THREAD

**Issue by kchevali** [kchevali/CakeManiac#29]
# Description
Track the timings of each customer.

# Tasks
- [ ] Track the arrival of each customer.
- [ ] Record the amount of time for the customer to decide on their order.
- [ ] Predict the amount of time until the next customer arrives if the store is still open.
