### ISSUE TITLE
Image Processing

### ISSUE THREAD

**Issue by kchevali** [kchevali/CakeManiac#5]
# Description
Develop different image processing algorithms to detect what is occurring in the game.

# Tasks
- [ ] Convert pixel matrix from color to grayscale.
- [ ] Detect difference in pixels over time.
- [ ] Detect motion over time.
- [ ] Edge detection.

# Prerequisite Issues
- #2
