### ISSUE TITLE
Display Processed Image Views

### ISSUE THREAD

**Issue by kchevali** [kchevali/CakeManiac#6]
# Description
Display the different processed images in the GUI.

# Tasks
- [ ] List the different processed images from #5 in the GUI.
- [ ] Toggle which processed image to show using buttons. See #7.
- [ ] Selecting a button, should change the gui view to that processing algorithm.
- [ ] The current algorithm should be shown or highlighted in the GUI.

# Other Prerequisite Issues
- #3
