### ISSUE TITLE
Create GUI Event System

### ISSUE THREAD

**Issue by kchevali** [kchevali/CakeManiac#7]
# Description
Create an event system to handle mouse, keyboard and screen resize events for the GUI. Use an observer design pattern to receive GUI events and publish the events to different GUI elements.

# Tasks
- [ ] Create an event manager that accepts all the GUI events.
- [ ] Create event classes for each GUI event
- [ ] Create a subscriber class that can request a callback function to be called when an event occurs.

# GUI Events
## Mouse Events
- Move mouse
- Left click mouse
- Right click mouse

## Keyboard Events
- Press key down
- Press key up

## Screen Resize Events
- Screen change size

# Resources
- [Observer design pattern](https://howtodoinjava.com/design-patterns/behavioral/observer-design-pattern/)
